# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install SpaCy Model
      run: python -m spacy download ru_core_news_md

    - name: Install Simplification Model
      run: |
        python -c "from simplification.cycle_gan import download_model; download_model('ru')"
        
    - name: Run Tests
      env:
        PYTHONPATH: .
      run: |
        pytest tests/

  train-model:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train Model
      run: |
        python scripts/train_model.py

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v2
      with:
        name: recommendation_model
        path: app/ml/models/recommendation_model.pkl

  deploy:
    runs-on: ubuntu-latest
    needs: train-model

    steps:
    - uses: actions/checkout@v2

    - name: Download Model Artifact
      uses: actions/download-artifact@v2
      with:
        name: recommendation_model
        path: app/ml/models/

    - name: Deploy to Production
      run: |
        # Команды для деплоя (например, docker-compose up -d)
